#!/usr/bin/env bash
#

INC="0"

while [ $INC -lt 100 ] ; do
	((INC++))
	if [ $((INC % 3)) == 0 ] && [ $((INC % 5)) == 0 ] ; then
		echo "FizzBuzz"
	elif [ $((INC % 3)) == 0 ] ; then
		echo "Fizz"
	elif [ $((INC % 5)) == 0 ] ; then
		echo "Buzz"
	else
		echo "$INC"
	fi
done
