#!/usr/bin/env bash
#

IFS=":"
while IFS=":" read -r username _ userid _ GID _ homedir _ shell
do
	echo " The user $username is part of the $GID gang, lives in $homedir, and rides $shell"
	echo "$userid/'s place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < /etc/passwd
