#!/usr/bin/env bash
#

IFS=":"
while IFS=":" read -r username password userid GID GECOS homedir shell 
do
	echo "The user $username is part of the $GID gang, lives in $homedir and rides $shell. $userid/'s place is protected by the passcode $password, more info about the user here: $GECOS"
done < /etc/passwd
