#!/usr/bin/env bash
# 

INC="1"

while [ $INC -le "10" ] ; do
	if [ $INC -eq "4" ] ; then
		echo "bad luck"
	elif [ $INC -eq "8" ] ; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((INC++))
done
