#!/usr/bin/env bash
# 

INC="1"

while [ $INC -le "20" ] ; do
	case $INC in
		(4) echo "$INC" ; echo "bad luck from China" ;;
		(9) echo "$INC" ; echo "bad luck from Japan" ;;
		(17) echo "$INC" ; echo "bad luck from Italy" ;;
		(*) echo "$INC" ;;
	esac
	((INC++))
done
